const mapping = {
  facebook: {
    // account_id: '',
    // account_name: '',
    // action_values: '',
    // actions: '',

    // campaign_id: '',

    conversion_values: '',
    conversions: '',
    clicks: 'clicksAll',
    cost_per_action_type: '',
    cost_per_conversion: '',
    cost_per_outbound_click: '',
    cpc: 'cpc',
    cpm: 'cpm',
    ctr: 'ctr',
    frequency: 'frequency',
    impressions: 'impressions',
    objective: '',
    optimization_goal: '',
    outbound_clicks: '',
    outbound_clicks_ctr: 'outboundClicksCtr',
    reach: 'reach',
    spend: 'cost',
    unique_outbound_clicks: 'uniqueOutboundClicks',
    unique_outbound_clicks_ctr: 'uniqueOutboundClicksCtr',
    video_p100_watched_actions: 'video100Rate',
    video_p25_watched_actions: 'video25Rate',
    video_p50_watched_actions: 'video50Rate',
    video_p75_watched_actions: 'video75Rate',
    result: 'results',
  },

  google: {
    absoluteTopImpressionPercentage: '',
    activeViewCpm: '',
    activeViewCtr: '',
    activeViewImpressions: 'frequency',
    activeViewMeasurability: '',
    activeViewMeasurableCostMicros: '',
    activeViewMeasurableImpressions: '',
    activeViewViewability: '',
    allConversions: '',
    allConversionsByConversionDate: '',
    allConversionsFromClickToCall: '',
    allConversionsFromDirections: '',
    allConversionsFromInteractionsRate: '',
    allConversionsFromMenu: '',
    allConversionsFromOrder: '',
    allConversionsFromOtherEngagement: '',
    allConversionsFromStoreVisit: '',
    allConversionsFromStoreWebsite: '',
    allConversionsValue: '',
    allConversionsValueByConversionDate: '',
    auctionInsightSearchAbsoluteTopImpressionPercentage: '',
    auctionInsightSearchImpressionShare: '',
    auctionInsightSearchOutrankingShare: '',
    auctionInsightSearchOverlapRate: '',
    auctionInsightSearchPositionAboveRate: '',
    auctionInsightSearchTopImpressionPercentage: '',
    averageCost: '',
    averageCpc: 'cpc',
    averageCpe: '',
    averageCpm: 'cpm',
    averageCpv: 'costPerPlayRate',
    averagePageViews: '',
    averageTimeOnSite: '',
    bounceRate: 'bounceRate',
    clicks: 'clicksAll',
    contentBudgetLostImpressionShare: '',
    contentImpressionShare: '',
    contentRankLostImpressionShare: '',
    conversions: 'conversionValue',
    conversionsByConversionDate: '',
    conversionsFromInteractionsRate: 'cvr',
    conversionsValue: 'pixelRevenue',
    conversionsValueByConversionDate: '',
    costMicros: 'cost',
    costPerAllConversions: '',
    costPerConversion: '',
    costPerCurrentModelAttributedConversion: '',
    crossDeviceConversions: '',
    ctr: 'ctr',
    currentModelAttributedConversions: '',
    currentModelAttributedConversionsFromInteractionsRate: '',
    currentModelAttributedConversionsFromInteractionsValuePerInteraction: '',
    currentModelAttributedConversionsValue: '',
    currentModelAttributedConversionsValuePerCost: '',
    engagementRate: '',
    engagements: '',
    gmailForwards: 'msgSend',
    gmailSaves: '',
    gmailSecondaryClicks: 'msgOpen',
    impressions: 'impressions',
    interactionEventTypes: 'conversionEvent',
    interactionRate: '',
    interactions: '',
    invalidClickRate: '',
    invalidClicks: '',
    percentNewVisitors: 'sessionDuration',
    phoneCalls: '',
    phoneImpressions: '',
    phoneThroughRate: '',
    publisherOrganicClicks: '',
    publisherPurchasedClicks: '',
    publisherUnknownClicks: '',
    relativeCtr: '',
    searchAbsoluteTopImpressionShare: '',
    searchBudgetLostAbsoluteTopImpressionShare: '',
    searchBudgetLostImpressionShare: '',
    searchBudgetLostTopImpressionShare: '',
    searchClickShare: '',
    searchExactMatchImpressionShare: '',
    searchImpressionShare: '',
    searchRankLostAbsoluteTopImpressionShare: '',
    searchRankLostImpressionShare: '',
    searchRankLostTopImpressionShare: '',
    searchTopImpressionShare: '',
    skAdNetworkConversions: '',
    topImpressionPercentage: '',
    valuePerAllConversions: '',
    valuePerAllConversionsByConversionDate: '',
    valuePerConversion: '',
    valuePerConversionsByConversionDate: '',
    valuePerCurrentModelAttributedConversion: '',
    videoQuartileP100Rate: 'video100Rate',
    videoQuartileP25Rate: 'video25Rate',
    videoQuartileP50Rate: 'video50Rate',
    videoQuartileP75Rate: 'video75Rate',
    videoViewRate: 'playRate',
    videoViews: 'videoViews',
    viewThroughConversions: '',
    /*
    absolute_top_impression_percentage: '',
    active_view_cpm: '',
    active_view_ctr: '',
    active_view_impressions: 'frequency',
    active_view_measurability: '',
    active_view_measurable_cost_micros: '',
    active_view_measurable_impressions: '',
    active_view_viewability: '',
    all_conversions: '',
    all_conversions_by_conversion_date: '',
    all_conversions_from_click_to_call: '',
    all_conversions_from_directions: '',
    all_conversions_from_interactions_rate: '',
    all_conversions_from_menu: '',
    all_conversions_from_order: '',
    all_conversions_from_other_engagement: '',
    all_conversions_from_store_visit: '',
    all_conversions_from_store_website: '',
    all_conversions_value: '',
    all_conversions_value_by_conversion_date: '',
    auction_insight_search_absolute_top_impression_percentage: '',
    auction_insight_search_impression_share: '',
    auction_insight_search_outranking_share: '',
    auction_insight_search_overlap_rate: '',
    auction_insight_search_position_above_rate: '',
    auction_insight_search_top_impression_percentage: '',
    average_cost: '',
    average_cpc: 'cpc',
    average_cpe: '',
    average_cpm: 'cpm',
    average_cpv: 'costPerPlayRate',
    average_page_views: '',
    average_time_on_site: '',
    bounce_rate: 'bounceRate',
    clicks: 'clicksAll',
    content_budget_lost_impression_share: '',
    content_impression_share: '',
    content_rank_lost_impression_share: '',
    conversions: 'conversionValue',
    conversions_by_conversion_date: '',
    conversions_from_interactions_rate: 'cvr',
    conversions_value: 'pixelRevenue',
    conversions_value_by_conversion_date: '',
    cost_micros: 'cost',
    cost_per_all_conversions: '',
    cost_per_conversion: '',
    cost_per_current_model_attributed_conversion: '',
    cross_device_conversions: '',
    ctr: 'ctr',
    current_model_attributed_conversions: '',
    current_model_attributed_conversions_from_interactions_rate: '',
    current_model_attributed_conversions_from_interactions_value_per_interaction: '',
    current_model_attributed_conversions_value: '',
    current_model_attributed_conversions_value_per_cost: '',
    engagement_rate: '',
    engagements: '',
    gmail_forwards: 'msgSend',
    gmail_saves: '',
    gmail_secondary_clicks: 'msgOpen',
    impressions: 'impressions',
    interaction_event_types: 'conversionEvent',
    interaction_rate: '',
    interactions: '',
    invalid_click_rate: '',
    invalid_clicks: '',
    percent_new_visitors: 'sessionDuration',
    phone_calls: '',
    phone_impressions: '',
    phone_through_rate: '',
    publisher_organic_clicks: '',
    publisher_purchased_clicks: '',
    publisher_unknown_clicks: '',
    relative_ctr: '',
    search_absolute_top_impression_share: '',
    search_budget_lost_absolute_top_impression_share: '',
    search_budget_lost_impression_share: '',
    search_budget_lost_top_impression_share: '',
    search_click_share: '',
    search_exact_match_impression_share: '',
    search_impression_share: '',
    search_rank_lost_absolute_top_impression_share: '',
    search_rank_lost_impression_share: '',
    search_rank_lost_top_impression_share: '',
    search_top_impression_share: '',
    sk_ad_network_conversions: '',
    top_impression_percentage: '',
    value_per_all_conversions: '',
    value_per_all_conversions_by_conversion_date: '',
    value_per_conversion: '',
    value_per_conversions_by_conversion_date: '',
    value_per_current_model_attributed_conversion: '',
    video_quartile_p100_rate: 'video100Rate',
    video_quartile_p25_rate: 'video25Rate',
    video_quartile_p50_rate: 'video50Rate',
    video_quartile_p75_rate: 'video75Rate',
    video_view_rate: 'play_rate',
    video_views: 'videoViews',
    view_through_conversions: '',
    */
  },

  tiktok: {
    // basic report
    spend: 'cost',
    // cash_spend: '',
    // voucher_spend: '',
    cpc: 'cpc',
    cpm: 'cpm',
    impressions: 'impressions',
    // gross_impressions: '',
    clicks: 'clicksAll',
    ctr: 'ctr',
    reach: 'reach',
    // cost_per_1000_reached: '',
    conversion: 'conversionValue',
    // cost_per_conversion: '',
    conversion_rate: 'cvr',
    // conversion_rate_v2: '',
    // real_time_conversion: '',
    // real_time_cost_per_conversion: '',
    // real_time_conversion_rate: '',
    // real_time_conversion_rate_v2: '',
    result: 'results',
    cost_per_result: 'costPerResult',
    result_rate: 'resultRate',
    // real_time_result: '',
    // real_time_cost_per_result: '',
    // real_time_result_rate: '',
    // secondary_goal_result: '',
    // cost_per_secondary_goal_result: '',
    // secondary_goal_result_rate: '',
    frequency: 'frequency',
    // currency: '',
    // is_aco: '',
    // is_smart_creative: '',
    video_play_actions: 'videoViews',
    // video_watched_2s: '',
    // video_watched_6s: '',
    // average_video_play: '',
    // average_video_play_per_user: '',
    video_views_p25: 'video25',
    video_views_p50: 'video50',
    video_views_p75: 'video75',
    video_views_p100: 'video100',
    // engaged_view: '',
    // engaged_view_15s: '',
    engagements: 'engagement',
    // engagement_rate: '',
    // profile_visits: '',
    // profile_visits_rate: '',
    likes: 'postReactions',
    comments: 'postComments',
    shares: 'postShares',
    // follows: '',
    // clicks_on_music_disc: '',
    // duet_clicks: '',
    // stitch_clicks: '',
    // sound_usage_clicks: '',
    // anchor_clicks: '',
    // anchor_click_rate: '',
    // clicks_on_hashtag_challenge: '',
    // ix_page_duration_avg: '',
    // ix_page_viewrate_avg: '',
    // ix_video_views: '',
    // ix_video_views_p25: '',
    // ix_video_views_p50: '',
    // ix_video_views_p75: '',
    // ix_video_views_p100: '',
    // ix_average_video_play: '',
    // single_image_impressions: '',
    // single_image_impression_rate: '',
    // single_image_ctr: '',
    // interactive_add_on_impressions: '',
    // interactive_add_on_destination_clicks: '',
    // interactive_add_on_activity_clicks: '',
    // interactive_add_on_option_a_clicks: '',
    // interactive_add_on_option_b_clicks: '',
    // countdown_sticker_recall_clicks: '',
    // live_views: '',
    // live_unique_views: '',
    // live_effective_views: '',
    // live_product_clicks: '',
    // real_time_app_install: '',
    // real_time_app_install_cost: '',
    // app_install: '',
    // cost_per_app_install: '',
    // registration: '',
    // cost_per_registration: '',
    // registration_rate: '',
    // total_registration: '',
    // cost_per_total_registration: '',
    // purchase: '',
    // cost_per_purchase: '',
    // purchase_rate: '',
    // total_purchase: '',
    // cost_per_total_purchase: '',
    // value_per_total_purchase: '',
    // total_purchase_value: '',
    // total_active_pay_roas: '',
    // app_event_add_to_cart: '',
    // cost_per_app_event_add_to_cart: '',
    // app_event_add_to_cart_rate: '',
    // total_app_event_add_to_cart: '',
    // cost_per_total_app_event_add_to_cart: '',
    // value_per_total_app_event_add_to_cart: '',
    // total_app_event_add_to_cart_value: '',
    // checkout: '',
    // cost_per_checkout: '',
    // checkout_rate: '',
    // total_checkout: '',
    // cost_per_total_checkout: '',
    // value_per_checkout: '',
    // total_checkout_value: '',
    // view_content: '',
    // cost_per_view_content: '',
    // view_content_rate: '',
    // total_view_content: '',
    // cost_per_total_view_content: '',
    // value_per_total_view_content: '',
    // total_view_content_value: '',
    // next_day_open: '',
    // cost_per_next_day_open: '',
    // next_day_open_rate: '',
    // total_next_day_open: '',
    // cost_per_total_next_day_open: '',
    // add_payment_info: '',
    // cost_per_add_payment_info: '',
    // add_payment_info_rate: '',
    // total_add_payment_info: '',
    // cost_total_add_payment_info: '',
    // add_to_wishlist: '',
    // cost_per_add_to_wishlist: '',
    // add_to_wishlist_rate: '',
    // total_add_to_wishlist: '',
    // cost_per_total_add_to_wishlist: '',
    // value_per_total_add_to_wishlist: '',
    // total_add_to_wishlist_value: '',
    // launch_app: '',
    // cost_per_launch_app: '',
    // launch_app_rate: '',
    // total_launch_app: '',
    // cost_per_total_launch_app: '',
    // complete_tutorial: '',
    // cost_per_complete_tutorial: '',
    // complete_tutorial_rate: '',
    // total_complete_tutorial: '',
    // cost_per_total_complete_tutorial: '',
    // value_per_total_complete_tutorial: '',
    // total_complete_tutorial_value: '',
    // create_group: '',
    // cost_per_create_group: '',
    // create_group_rate: '',
    // total_create_group: '',
    // cost_per_total_create_group: '',
    // value_per_total_create_group: '',
    // total_create_group_value: '',
    // join_group: '',
    // cost_per_join_group: '',
    // join_group_rate: '',
    // total_join_group: '',
    // cost_per_total_join_group: '',
    // value_per_total_join_group: '',
    // total_join_group_value: '',
    // create_gamerole: '',
    // cost_per_create_gamerole: '',
    // create_gamerole_rate: '',
    // total_create_gamerole: '',
    // cost_per_total_create_gamerole: '',
    // value_per_total_create_gamerole: '',
    // total_create_gamerole_value: '',
    // spend_credits: '',
    // cost_per_spend_credits: '',
    // spend_credits_rate: '',
    // total_spend_credits: '',
    // cost_per_total_spend_credits: '',
    // value_per_total_spend_credits: '',
    // total_spend_credits_value: '',
    // achieve_level: '',
    // cost_per_achieve_level: '',
    // achieve_level_rate: '',
    // total_achieve_level: '',
    // cost_per_total_achieve_level: '',
    // value_per_total_achieve_level: '',
    // total_achieve_level_value: '',
    // unlock_achievement: '',
    // cost_per_unlock_achievement: '',
    // unlock_achievement_rate: '',
    // total_unlock_achievement: '',
    // cost_per_total_unlock_achievement: '',
    // value_per_total_unlock_achievement: '',
    // total_unlock_achievement_value: '',
    // sales_lead: '',
    // cost_per_sales_lead: '',
    // sales_lead_rate: '',
    // total_sales_lead: '',
    // cost_per_total_sales_lead: '',
    // value_per_total_sales_lead: '',
    // total_sales_lead_value: '',
    // in_app_ad_click: '',
    // cost_per_in_app_ad_click: '',
    // in_app_ad_click_rate: '',
    // total_in_app_ad_click: '',
    // cost_per_total_in_app_ad_click: '',
    // value_per_total_in_app_ad_click: '',
    // total_in_app_ad_click_value: '',
    // in_app_ad_impr: '',
    // cost_per_in_app_ad_impr: '',
    // in_app_ad_impr_rate: '',
    // total_in_app_ad_impr: '',
    // cost_per_total_in_app_ad_impr: '',
    // value_per_total_in_app_ad_impr: '',
    // total_in_app_ad_impr_value: '',
    // loan_apply: '',
    // cost_per_loan_apply: '',
    // loan_apply_rate: '',
    // total_loan_apply: '',
    // cost_per_total_loan_apply: '',
    // loan_credit: '',
    // cost_per_loan_credit: '',
    // loan_credit_rate: '',
    // total_loan_credit: '',
    // cost_per_total_loan_credit: '',
    // loan_disbursement: '',
    // cost_per_loan_disbursement: '',
    // loan_disbursement_rate: '',
    // total_loan_disbursement: '',
    // cost_per_total_loan_disbursement: '',
    // login: '',
    // cost_per_login: '',
    // login_rate: '',
    // total_login: '',
    // cost_per_total_login: '',
    // ratings: '',
    // cost_per_ratings: '',
    // ratings_rate: '',
    // total_ratings: '',
    // cost_per_total_ratings: '',
    // value_per_total_ratings: '',
    // total_ratings_value: '',
    // search: '',
    // cost_per_search: '',
    // search_rate: '',
    // total_search: '',
    // cost_per_total_search: '',
    // start_trial: '',
    // cost_per_start_trial: '',
    // start_trial_rate: '',
    // total_start_trial: '',
    // cost_per_total_start_trial: '',
    // subscribe: '',
    // cost_per_subscribe: '',
    // subscribe_rate: '',
    // total_subscribe: '',
    // cost_per_total_subscribe: '',
    // value_per_total_subscribe: '',
    // total_subscribe_value: '',
    // unique_custom_app_events: '',
    // cost_per_unique_custom_app_event: '',
    // custom_app_event_rate: '',
    // custom_app_events: '',
    // cost_per_custom_app_event: '',
    // value_per_custom_app_event: '',
    // custom_app_events_value: '',
    // onsite_shopping_roas: '',
    // onsite_shopping: '',
    // cost_per_onsite_shopping: '',
    // onsite_shopping_rate: '',
    // value_per_onsite_shopping: '',
    // total_onsite_shopping_value: '',
    // onsite_initiate_checkout_count: '',
    // cost_per_onsite_initiate_checkout_count: '',
    // onsite_initiate_checkout_count_rate: '',
    // value_per_onsite_initiate_checkout_count: '',
    // total_onsite_initiate_checkout_count_value: '',
    // onsite_on_web_detail: '',
    // cost_per_onsite_on_web_detail: '',
    // onsite_on_web_detail_rate: '',
    // value_per_onsite_on_web_detail: '',
    // total_onsite_on_web_detail_value: '',
    // onsite_add_to_wishlist: '',
    // cost_per_onsite_add_to_wishlist: '',
    // onsite_add_to_wishlist_rate: '',
    // value_per_onsite_add_to_wishlist: '',
    // total_onsite_add_to_wishlist_value: '',
    // onsite_add_billing: '',
    // cost_per_onsite_add_billing: '',
    // onsite_add_billing_rate: '',
    // value_per_onsite_add_billing: '',
    // total_onsite_add_billing_value: '',
    // onsite_on_web_cart: '',
    // cost_per_onsite_on_web_cart: '',
    // onsite_on_web_cart_rate: '',
    // value_per_onsite_on_web_cart: '',
    // total_onsite_on_web_cart_value: '',
    // onsite_form: '',
    // cost_per_onsite_form: '',
    // onsite_form_rate: '',
    // value_per_onsite_form: '',
    // total_onsite_form_value: '',
    // onsite_download_start: '',
    // cost_per_onsite_download_start: '',
    // onsite_download_start_rate: '',
    // ix_page_view_count: '',
    // cost_per_ix_page_view_count: '',
    // ix_page_view_count_rate: '',
    // ix_button_click_count: '',
    // cost_per_ix_button_click_count: '',
    // ix_button_click_count_rate: '',
    // ix_product_click_count: '',
    // cost_per_ix_product_click_count: '',
    // ix_product_click_count_rate: '',
    // complete_payment_roas: '',
    // complete_payment: '',
    // cost_per_complete_payment: '',
    // complete_payment_rate: '',
    // value_per_complete_payment: '',
    // total_complete_payment_rate: '',
    // total_landing_page_view: '',
    // cost_per_landing_page_view: '',
    // landing_page_view_rate: '',
    // total_pageview: '',
    // cost_per_pageview: '',
    // pageview_rate: '',
    // avg_value_per_pageview: '',
    // total_value_per_pageview: '',
    // page_browse_view: '',
    // cost_per_page_browse_view: '',
    // page_browse_view_rate: '',
    // total_page_browse_view_value: '',
    // value_per_page_browse_view: '',
    // button_click: '',
    // cost_per_button_click: '',
    // button_click_rate: '',
    // value_per_button_click: '',
    // total_button_click_value: '',
    // online_consult: '',
    // cost_per_online_consult: '',
    // online_consult_rate: '',
    // value_per_online_consult: '',
    // total_online_consult_value: '',
    // user_registration: '',
    // cost_per_user_registration: '',
    // user_registration_rate: '',
    // value_per_user_registration: '',
    // total_user_registration_value: '',
    // product_details_page_browse: '',
    // cost_per_product_details_page_browse: '',
    // product_details_page_browse_rate: '',
    // value_per_product_details_page_browse: '',
    // total_product_details_page_browse_value: '',
    // web_event_add_to_cart: '',
    // cost_per_web_event_add_to_cart: '',
    // web_event_add_to_cart_rate: '',
    // value_per_web_event_add_to_cart: '',
    // total_web_event_add_to_cart_value: '',
    // on_web_order: '',
    // cost_per_on_web_order: '',
    // on_web_order_rate: '',
    // value_per_on_web_order: '',
    // total_on_web_order_value: '',
    // initiate_checkout: '',
    // cost_per_initiate_checkout: '',
    // initiate_checkout_rate: '',
    // value_per_initiate_checkout: '',
    // total_initiate_checkout_value: '',
    // add_billing: '',
    // cost_per_add_billing: '',
    // add_billing_rate: '',
    // value_per_add_billing: '',
    // total_add_billing_value: '',
    // page_event_search: '',
    // cost_per_page_event_search: '',
    // page_event_search_rate: '',
    // value_per_page_event_search: '',
    // total_page_event_search_value: '',
    // form: '',
    // cost_per_form: '',
    // form_rate: '',
    // value_per_form: '',
    // total_form_value: '',
    // download_start: '',
    // cost_per_download_start: '',
    // download_start_rate: '',
    // value_per_download_start: '',
    // total_download_start_value: '',
    // on_web_add_to_wishlist: '',
    // cost_per_on_web_add_to_wishlist: '',
    // on_web_add_to_wishlist_per_click: '',
    // value_per_on_web_add_to_wishlist: '',
    // total_on_web_add_to_wishlist_value: '',
    // on_web_subscribe: '',
    // cost_per_on_web_subscribe: '',
    // on_web_subscribe_per_click: '',
    // value_per_on_web_subscribe: '',
    // total_on_web_subscribe_value: '',
    // custom_page_events: '',
    // cost_per_custom_page_event: '',
    // custom_page_event_rate: '',
    // value_per_custom_page_event: '',
    // custom_page_events_value: '',
    // vta_app_install: '',
    // cost_per_vta_app_install: '',
    // vta_conversion: '',
    // cost_per_vta_conversion: '',
    // vta_registration: '',
    // cost_per_vta_registration: '',
    // vta_purchase: '',
    // cost_per_vta_purchase: '',
    // cta_app_install: '',
    // cost_per_cta_app_install: '',
    // cta_conversion: '',
    // cost_per_cta_conversion: '',
    // cta_registration: '',
    // cost_per_cta_registration: '',
    // cta_purchase: '',
    // cost_per_cta_purchase: '',
    // offline_shopping_events: '',
    // cost_per_offline_shopping_event: '',
    // offline_shopping_event_rate: '',
    // value_per_offline_shopping_event: '',
    // offline_shopping_events_value: '',
    // offline_shopping_events_roas: '',
    // offline_contact_events: '',
    // cost_per_offline_contact_event: '',
    // offline_contact_event_rate: '',
    // value_per_offline_contact_event: '',
    // offline_contact_events_value: '',
    // offline_subscribe_events: '',
    // cost_per_offline_subscribe_event: '',
    // offline_subscribe_event_rate: '',
    // value_per_offline_subscribe_event: '',
    // offline_subscribe_events_value: '',
    // offline_form_events: '',
    // cost_per_offline_form_event: '',
    // offline_form_event_rate: '',
    // value_per_offline_form_event: '',
    // offline_form_events_value: '',
    // offline_add_payment_info_events: '',
    // cost_per_offline_add_payment_info_event: '',
    // offline_add_payment_info_event_rate: '',
    // value_per_offline_add_payment_info_event: '',
    // offline_add_payment_info_events_value: '',
    // offline_add_to_cart_events: '',
    // cost_per_offline_add_to_cart_event: '',
    // offline_add_to_cart_event_rate: '',
    // value_per_offline_add_to_cart_event: '',
    // offline_add_to_cart_events_value: '',
    // offline_add_to_wishlist_events: '',
    // cost_per_offline_add_to_wishlist_event: '',
    // offline_add_to_wishlist_event_rate: '',
    // value_per_offline_add_to_wishlist_event: '',
    // offline_add_to_wishlist_events_value: '',
    // offline_click_button_events: '',
    // cost_per_offline_click_button_event: '',
    // offline_click_button_event_rate: '',
    // value_per_offline_click_button_event: '',
    // offline_click_button_events_value: '',
    // offline_complete_registration_events: '',
    // cost_per_offline_complete_registration_event: '',
    // offline_complete_registration_event_rate: '',
    // value_per_offline_complete_registration_event: '',
    // offline_complete_registration_events_value: '',
    // offline_download_events: '',
    // cost_per_offline_download_event: '',
    // offline_download_event_rate: '',
    // value_per_offline_download_event: '',
    // offline_download_events_value: '',
    // offline_initiate_checkout_events: '',
    // cost_per_offline_initiate_checkout_event: '',
    // offline_initiate_checkout_event_rate: '',
    // value_per_offline_initiate_checkout_event: '',
    // offline_initiate_checkout_events_value: '',
    // offline_place_order_events: '',
    // cost_per_offline_place_order_event: '',
    // offline_place_order_event_rate: '',
    // value_per_offline_place_order_event: '',
    // offline_place_order_events_value: '',
    // offline_search_events: '',
    // cost_per_offline_search_event: '',
    // offline_search_event_rate: '',
    // value_per_offline_search_event: '',
    // offline_search_events_value: '',
    // offline_view_content_events: '',
    // cost_per_offline_view_content_event: '',
    // offline_view_content_event_rate: '',
    // value_per_offline_view_content_event: '',
    // offline_view_content_events_value: '',
    // skan_result: '',
    // skan_cost_per_result: '',
    // skan_result_rate: '',
    // skan_conversion: '',
    // skan_cost_per_conversion: '',
    // skan_conversion_rate: '',
    // skan_conversion_rate_v2: '',
    // skan_click_time_conversion: '',
    // skan_click_time_conversion_rate: '',
    // skan_click_time_conversion_rate_v2: '',
    // skan_app_install: '',
    // skan_cost_per_app_install: '',
    // skan_app_install_withheld: '',
    // skan_registration: '',
    // skan_cost_per_registration: '',
    // skan_registration_rate: '',
    // skan_total_registration: '',
    // skan_cost_per_total_registration: '',
    // skan_purchase: '',
    // skan_cost_per_purchase: '',
    // skan_purchase_rate: '',
    // skan_total_purchase: '',
    // skan_cost_per_total_purchase: '',
    // skan_total_purchase_value: '',
    // skan_total_repetitive_active_pay_roas: '',
    // skan_add_to_cart: '',
    // skan_cost_per_add_to_cart: '',
    // skan_add_to_cart_rate: '',
    // skan_total_add_to_cart: '',
    // skan_cost_per_total_add_to_cart: '',
    // skan_total_add_to_cart_value: '',
    // skan_checkout: '',
    // skan_cost_per_checkout: '',
    // skan_checkout_rate: '',
    // skan_total_checkout: '',
    // skan_cost_per_total_checkout: '',
    // skan_total_checkout_value: '',
    // skan_view_content: '',
    // skan_cost_per_view_content: '',
    // skan_view_content_rate: '',
    // skan_total_view_content: '',
    // skan_cost_per_total_view_content: '',
    // skan_total_view_content_value: '',
    // skan_add_payment_info: '',
    // skan_cost_per_add_payment_info: '',
    // skan_add_payment_info_rate: '',
    // skan_total_add_payment_info: '',
    // skan_cost_total_add_payment_info: '',
    // skan_add_to_wishlist: '',
    // skan_cost_per_add_to_wishlist: '',
    // skan_add_to_wishlist_rate: '',
    // skan_total_add_to_wishlist: '',
    // skan_cost_per_total_add_to_wishlist: '',
    // skan_total_add_to_wishlist_value: '',
    // skan_launch_app: '',
    // skan_cost_per_launch_app: '',
    // skan_launch_app_rate: '',
    // skan_total_launch_app: '',
    // skan_cost_per_total_launch_app: '',
    // skan_total_complete_tutorial: '',
    // skan_cost_per_total_complete_tutorial: '',
    // skan_complete_tutorial: '',
    // skan_cost_per_complete_tutorial: '',
    // skan_complete_tutorial_rate: '',
    // skan_total_complete_tutorial_value: '',
    // skan_create_group: '',
    // skan_cost_per_create_group: '',
    // skan_create_group_rate: '',
    // skan_total_create_group: '',
    // skan_cost_per_total_create_group: '',
    // skan_total_create_group_value: '',
    // skan_join_group: '',
    // skan_cost_per_join_group: '',
    // skan_join_group_rate: '',
    // skan_total_join_group: '',
    // skan_cost_per_total_join_group: '',
    // skan_total_join_group_value: '',
    // skan_create_gamerole: '',
    // skan_cost_per_create_gamerole: '',
    // skan_create_gamerole_rate: '',
    // skan_total_create_gamerole: '',
    // skan_cost_per_total_create_gamerole: '',
    // skan_total_create_gamerole_value: '',
    // skan_spend_credits: '',
    // skan_cost_per_spend_credits: '',
    // skan_spend_credits_rate: '',
    // skan_total_spend_credits: '',
    // skan_cost_per_total_spend_credits: '',
    // skan_total_spend_credits_value: '',
    // skan_achieve_level: '',
    // skan_cost_per_achieve_level: '',
    // skan_achieve_level_rate: '',
    // skan_total_achieve_level: '',
    // skan_cost_per_total_achieve_level: '',
    // skan_total_achieve_level_value: '',
    // skan_unlock_achievement: '',
    // skan_cost_per_unlock_achievement: '',
    // skan_unlock_achievement_rate: '',
    // skan_total_unlock_achievement: '',
    // skan_cost_per_total_unlock_achievement: '',
    // skan_total_unlock_achievement_value: '',
    // skan_sales_lead: '',
    // skan_cost_per_sales_lead: '',
    // skan_sales_lead_rate: '',
    // skan_total_sales_lead: '',
    // skan_cost_per_total_sales_lead: '',
    // skan_total_sales_lead_value: '',
    // skan_in_app_ad_click: '',
    // skan_cost_per_in_app_ad_click: '',
    // skan_in_app_ad_click_rate: '',
    // skan_total_in_app_ad_click: '',
    // skan_cost_per_total_in_app_ad_click: '',
    // skan_total_in_app_ad_click_value: '',
    // skan_in_app_ad_impr: '',
    // skan_cost_per_in_app_ad_impr: '',
    // skan_in_app_ad_impr_rate: '',
    // skan_total_in_app_ad_impr: '',
    // skan_cost_per_total_in_app_ad_impr: '',
    // skan_total_in_app_ad_impr_value: '',
    // skan_loan_apply: '',
    // skan_cost_per_loan_apply: '',
    // skan_loan_apply_rate: '',
    // skan_total_loan_apply: '',
    // skan_cost_per_total_loan_apply: '',
    // skan_loan_credit: '',
    // skan_cost_per_loan_credit: '',
    // skan_loan_credit_rate: '',
    // skan_total_loan_credit: '',
    // skan_cost_per_total_loan_credit: '',
    // skan_loan_disbursement: '',
    // skan_cost_per_loan_disbursement: '',
    // skan_loan_disbursement_rate: '',
    // skan_total_loan_disbursement: '',
    // skan_cost_per_total_loan_disbursement: '',
    // skan_login: '',
    // skan_cost_per_login: '',
    // skan_login_rate: '',
    // skan_total_login: '',
    // skan_cost_per_total_login: '',
    // skan_ratings: '',
    // skan_cost_per_ratings: '',
    // skan_ratings_rate: '',
    // skan_total_ratings: '',
    // skan_cost_per_total_ratings: '',
    // skan_total_ratings_value: '',
    // skan_search: '',
    // skan_cost_per_search: '',
    // skan_search_rate: '',
    // skan_total_search: '',
    // skan_cost_per_total_search: '',
    // skan_start_trial: '',
    // skan_cost_per_start_trial: '',
    // skan_start_trial_rate: '',
    // skan_total_start_trial: '',
    // skan_cost_per_total_start_trial: '',
    // skan_subscribe: '',
    // skan_cost_per_subscribe: '',
    // skan_subscribe_rate: '',
    // skan_total_subscribe: '',
    // skan_cost_per_total_subscribe: '',
    // skan_total_subscribe_value: '',
    // skan_vta_conversion: '',
    // skan_cost_per_vta_conversion: '',
    // skan_vta_app_install: '',
    // skan_cost_per_vta_app_install: '',
    // skan_vta_registration: '',
    // skan_cost_per_vta_registration: '',
    // skan_vta_purchase: '',
    // skan_cost_per_vta_purchase: '',
    // skan_cta_conversion: '',
    // skan_cost_per_cta_conversion: '',
    // skan_cta_app_install: '',
    // skan_cost_per_cta_app_install: '',
    // skan_cta_registration: '',
    // skan_cost_per_cta_registration: '',
    // skan_cta_purchase: '',
    // skan_cost_per_cta_purchase: '',

    // audience reports
    /* 중복
    spend: '',
    cpc: '',
    cpm: '',
    impressions: '',
    gross_impressions: '',
    clicks: '',
    ctr: '',
    conversion: '',
    cost_per_conversion: '',
    conversion_rate: '',
    conversion_rate_v2: '',
    real_time_conversion: '',
    real_time_cost_per_conversion: '',
    real_time_conversion_rate: '',
    real_time_conversion_rate_v2: '',
    result: '',
    cost_per_result: '',
    result_rate: '',
    real_time_result: '',
    real_time_cost_per_result: '',
    real_time_result_rate: '',
    currency: '',
    is_aco: '',
    is_smart_creative: '',
    video_play_actions: '',
    video_watched_2s: '',
    video_watched_6s: '',
    average_video_play: '',
    average_video_play_per_user: '',
    video_views_p25: '',
    video_views_p50: '',
    video_views_p75: '',
    video_views_p100: '',
    profile_visits: '',
    profile_visits_rate: '',
    likes: '',
    comments: '',
    shares: '',
    follows: '',
    clicks_on_music_disc: '',
    ix_page_duration_avg: '',
    ix_page_viewrate_avg: '',
    total_landing_page_view: '',
    cost_per_landing_page_view: '',
    landing_page_view_rate: '',
    */

    // playable ad reports
    /* 중복
    spend: '',
    cpm: '',
    impressions: '',
    clicks: '',
    ctr: '',
    conversion: '',
    cost_per_conversion: '',
    conversion_rate: '',
    conversion_rate_v2: '',
    currency: '',
    app_install: '',
    cost_per_app_install: '',
    */
    // app_install_rate: '',
    // playable_page_view_count: '',
    // playable_first_scene_view_count: '',
    // playable_second_scene_view_count: '',
    // playable_third_scene_view_count: '',
    // playable_cta_click: '',

    // DSA reports
    /* 중복
    impressions: '',
    clicks: '',
    spend: '',
    conversion: '',
    cost_per_conversion: '',
    conversion_rate: '',
    conversion_rate_v2: '',
    ctr: '',
    cpc: '',
    cpm: '',
    real_time_result: '',
    real_time_cost_per_result: '',
    real_time_result_rate: '',
    result: '',
    cost_per_result: '',
    result_rate: '',
    currency: '',
    real_time_app_install: '',
    real_time_app_install_cost: '',
    app_install: '',
    cost_per_app_install: '',
    registration: '',
    cost_per_registration: '',
    registration_rate: '',
    total_registration: '',
    cost_per_total_registration: '',
    purchase: '',
    cost_per_purchase: '',
    purchase_rate: '',
    total_purchase: '',
    cost_per_total_purchase: '',
    value_per_total_purchase: '',
    total_purchase_value: '',
    total_active_pay_roas: '',
    app_event_add_to_cart: '',
    cost_per_app_event_add_to_cart: '',
    app_event_add_to_cart_rate: '',
    total_app_event_add_to_cart: '',
    cost_per_total_app_event_add_to_cart: '',
    value_per_total_app_event_add_to_cart: '',
    total_app_event_add_to_cart_value: '',
    checkout: '',
    cost_per_checkout: '',
    checkout_rate: '',
    total_checkout: '',
    cost_per_total_checkout: '',
    value_per_checkout: '',
    total_checkout_value: '',
    view_content: '',
    cost_per_view_content: '',
    view_content_rate: '',
    total_view_content: '',
    cost_per_total_view_content: '',
    value_per_total_view_content: '',
    total_view_content_value: '',
    next_day_open: '',
    cost_per_next_day_open: '',
    next_day_open_rate: '',
    total_next_day_open: '',
    cost_per_total_next_day_open: '',
    add_payment_info: '',
    cost_per_add_payment_info: '',
    add_payment_info_rate: '',
    total_add_payment_info: '',
    cost_total_add_payment_info: '',
    add_to_wishlist: '',
    cost_per_add_to_wishlist: '',
    add_to_wishlist_rate: '',
    total_add_to_wishlist: '',
    cost_per_total_add_to_wishlist: '',
    value_per_total_add_to_wishlist: '',
    total_add_to_wishlist_value: '',
    launch_app: '',
    cost_per_launch_app: '',
    launch_app_rate: '',
    total_launch_app: '',
    cost_per_total_launch_app: '',
    complete_tutorial: '',
    cost_per_complete_tutorial: '',
    complete_tutorial_rate: '',
    total_complete_tutorial: '',
    cost_per_total_complete_tutorial: '',
    value_per_total_complete_tutorial: '',
    total_complete_tutorial_value: '',
    create_group: '',
    cost_per_create_group: '',
    create_group_rate: '',
    total_create_group: '',
    cost_per_total_create_group: '',
    value_per_total_create_group: '',
    total_create_group_value: '',
    join_group: '',
    cost_per_join_group: '',
    join_group_rate: '',
    total_join_group: '',
    cost_per_total_join_group: '',
    value_per_total_join_group: '',
    total_join_group_value: '',
    create_gamerole: '',
    cost_per_create_gamerole: '',
    create_gamerole_rate: '',
    total_create_gamerole: '',
    cost_per_total_create_gamerole: '',
    value_per_total_create_gamerole: '',
    total_create_gamerole_value: '',
    spend_credits: '',
    cost_per_spend_credits: '',
    spend_credits_rate: '',
    total_spend_credits: '',
    cost_per_total_spend_credits: '',
    value_per_total_spend_credits: '',
    total_spend_credits_value: '',
    achieve_level: '',
    cost_per_achieve_level: '',
    achieve_level_rate: '',
    total_achieve_level: '',
    cost_per_total_achieve_level: '',
    value_per_total_achieve_level: '',
    total_achieve_level_value: '',
    unlock_achievement: '',
    cost_per_unlock_achievement: '',
    unlock_achievement_rate: '',
    total_unlock_achievement: '',
    cost_per_total_unlock_achievement: '',
    value_per_total_unlock_achievement: '',
    total_unlock_achievement_value: '',
    sales_lead: '',
    cost_per_sales_lead: '',
    sales_lead_rate: '',
    total_sales_lead: '',
    cost_per_total_sales_lead: '',
    value_per_total_sales_lead: '',
    total_sales_lead_value: '',
    in_app_ad_click: '',
    cost_per_in_app_ad_click: '',
    in_app_ad_click_rate: '',
    total_in_app_ad_click: '',
    cost_per_total_in_app_ad_click: '',
    value_per_total_in_app_ad_click: '',
    total_in_app_ad_click_value: '',
    in_app_ad_impr: '',
    cost_per_in_app_ad_impr: '',
    in_app_ad_impr_rate: '',
    total_in_app_ad_impr: '',
    cost_per_total_in_app_ad_impr: '',
    value_per_total_in_app_ad_impr: '',
    total_in_app_ad_impr_value: '',
    loan_apply: '',
    cost_per_loan_apply: '',
    loan_apply_rate: '',
    total_loan_apply: '',
    cost_per_total_loan_apply: '',
    loan_credit: '',
    cost_per_loan_credit: '',
    loan_credit_rate: '',
    total_loan_credit: '',
    cost_per_total_loan_credit: '',
    loan_disbursement: '',
    cost_per_loan_disbursement: '',
    loan_disbursement_rate: '',
    total_loan_disbursement: '',
    cost_per_total_loan_disbursement: '',
    login: '',
    cost_per_login: '',
    login_rate: '',
    total_login: '',
    cost_per_total_login: '',
    ratings: '',
    cost_per_ratings: '',
    ratings_rate: '',
    total_ratings: '',
    cost_per_total_ratings: '',
    value_per_total_ratings: '',
    total_ratings_value: '',
    search: '',
    cost_per_search: '',
    search_rate: '',
    total_search: '',
    cost_per_total_search: '',
    start_trial: '',
    cost_per_start_trial: '',
    start_trial_rate: '',
    total_start_trial: '',
    cost_per_total_start_trial: '',
    subscribe: '',
    cost_per_subscribe: '',
    subscribe_rate: '',
    total_subscribe: '',
    cost_per_total_subscribe: '',
    value_per_total_subscribe: '',
    total_subscribe_value: '',
    complete_payment_roas: '',
    complete_payment: '',
    cost_per_complete_payment: '',
    complete_payment_rate: '',
    value_per_complete_payment: '',
    total_complete_payment_rate: '',
    value_per_button_click: '',
    total_button_click_value: '',
    user_registration: '',
    cost_per_user_registration: '',
    user_registration_rate: '',
    value_per_user_registration: '',
    total_user_registration_value: '',
    web_event_add_to_cart: '',
    cost_per_web_event_add_to_cart: '',
    web_event_add_to_cart_rate: '',
    value_per_web_event_add_to_cart: '',
    total_web_event_add_to_cart_value: '',
    on_web_order: '',
    cost_per_on_web_order: '',
    on_web_order_rate: '',
    value_per_on_web_order: '',
    total_on_web_order_value: '',
    initiate_checkout: '',
    cost_per_initiate_checkout: '',
    initiate_checkout_rate: '',
    value_per_initiate_checkout: '',
    total_initiate_checkout_value: '',
    add_billing: '',
    cost_per_add_billing: '',
    add_billing_rate: '',
    value_per_add_billing: '',
    total_add_billing_value: '',
    page_event_search: '',
    cost_per_page_event_search: '',
    page_event_search_rate: '',
    value_per_page_event_search: '',
    total_page_event_search_value: '',
    form: '',
    cost_per_form: '',
    form_rate: '',
    value_per_form: '',
    total_form_value: '',
    download_start: '',
    cost_per_download_start: '',
    download_start_rate: '',
    value_per_download_start: '',
    total_download_start_value: '',
    on_web_add_to_wishlist: '',
    cost_per_on_web_add_to_wishlist: '',
    on_web_add_to_wishlist_per_click: '',
    value_per_on_web_add_to_wishlist: '',
    total_on_web_add_to_wishlist_value: '',
    on_web_subscribe: '',
    cost_per_on_web_subscribe: '',
    on_web_subscribe_per_click: '',
    value_per_on_web_subscribe: '',
    total_on_web_subscribe_value: '',
    */

    // reservation ad reports
    /* 중복
    spend: '',
    impressions: '',
    clicks: '',
    ctr: '',
    reach: '',
    cost_per_1000_reached: '',
    frequency: '',
    currency: '',
    video_play_actions: '',
    video_watched_2s: '',
    video_watched_6s: '',
    video_views_p25: '',
    video_views_p50: '',
    video_views_p75: '',
    video_views_p100: '',
    average_video_play: '',
    average_video_play_per_user: '',
    likes: '',
    comments: '',
    shares: '',
    profile_visits: '',
    follows: '',
    clicks_on_music_disc: '',
    clicks_on_hashtag_challenge: '',
    engagements: '',
    engagement_rate: '',
    */
    // skip_ad: '',
    // interact_card_show_cnt: '',
    // interact_card_a_click_cnt: '',
    // interact_card_b_click_cnt: '',
    // vote_card_show_cnt: '',
    // vote_card_a_click_cnt: '',
    // vote_card_b_click_cnt: '',
    // vote_card_convert_click_cnt: '',
    // redpacket_show_cnt: '',
    // redpacket_click_cnt: '',
    // image_card_show_cnt: '',
    // image_card_click_cnt: '',
  },

  kakao: {
    moment: {
      // 리포트 타입별 중복 지표가 있어 그룹화
      basic: {
        imp: 'impressions',
        click: 'clicksAll',
        ctr: 'ctr',
        cost: 'cost',
        // video_play_3s: '',
      },

      addition: {
        reach: 'reach',
        cost_per_imp: 'costPerImp',
        cost_per_click: 'cpc',
        cost_per_reach: 'costPerReach',
        // cost_per_video_play_3s: '',
      },

      message: {
        msg_send: 'msgSend',
        msg_open: 'msgOpen',
        msg_click: 'msgClick',
        cost: 'msgCost',
      },

      message_addition: {
        // cost_per_msg_send: '',
        // cost_per_msg_open: '',
        // cost_per_msg_click: '',
        // 아래 2개 항목은 문서상으로는 구분되어 있었음 (항목자체는 message_addition으로 동일)
        // msg_open_rate: '',
        // msg_click_rate: '',
      },

      pixel_sdk_conversion: {
        // conv_cmpt_reg_1d: '',
        // conv_cmpt_reg_7d: '',
        // conv_view_cart_1d: '',
        // conv_view_cart_7d: '',
        // conv_purchase_1d: '',
        // conv_purchase_7d: '',
        // conv_purchase_p_1d: '',
        // conv_purchase_p_7d: '',
        // conv_participation_1d: '',
        // conv_participation_7d: '',
        // conv_signup_1d: '',
        // conv_signup_7d: '',
        // conv_app_install_1d: '',
        // conv_app_install_7d: '',
        // cost_per_conv_cmpt_reg_1d: '',
        // cost_per_conv_cmpt_reg_7d: '',
        // conv_cmpt_reg_1d_rate: '',
        // conv_cmpt_reg_7d_rate: '',
        // conv_add_to_wishlist_1d: '',
        // cost_per_conv_add_to_wishlist_1d: '',
        // conv_add_to_wishlist_1d_rate: '',
        // conv_add_to_wishlist_7d: '',
        // cost_per_conv_add_to_wishlist_7d: '',
        // conv_add_to_wishlist_7d_rate: '',
        // conv_add_to_cart_1d: '',
        // cost_per_conv_add_to_cart_1d: '',
        // conv_add_to_cart_1d_rate: '',
        // conv_add_to_cart_7d: '',
        // cost_per_conv_add_to_cart_7d: '',
        // conv_add_to_cart_7d_rate: '',
        // cost_per_conv_view_cart_1d: '',
        // cost_per_conv_view_cart_7d: '',
        // conv_view_cart_1d_rate: '',
        // conv_view_cart_7d_rate: '',
        // cost_per_conv_purchase_1d: '',
        // cost_per_conv_purchase_7d: '',
        // conv_purchase_1d_rate: '',
        // conv_purchase_7d_rate: '',
        // cost_per_conv_participation_1d: '',
        // cost_per_conv_participation_7d: '',
        // conv_participation_1d_rate: '',
        // conv_participation_7d_rate: '',
        // cost_per_conv_signup_1d: '',
        // cost_per_conv_signup_7d: '',
        // conv_signup_1d_rate: '',
        // conv_signup_7d_rate: '',
        // cost_per_conv_app_install_1d: '',
        // cost_per_conv_app_install_7d: '',
        // conv_app_install_1d_rate: '',
        // conv_app_install_7d_rate: '',
      },

      plus_friend: {
        // conv_kf_pf_add_1d: '',
        // conv_kf_pf_add_7d: '',
        // cost_per_conv_kf_pf_add_1d: '',
        // cost_per_conv_kf_pf_add_7d: '',
        // conv_kf_pf_add_1d_rate: '',
        // conv_kf_pf_add_7d_rate: '',
      },

      video: {
        video_play: 'videoViews',
        // cost_per_video_play_3s: '',
        // video_play_auto: '',
        // video_play_touch: '',
        // video_unmute: '',
        // video_play_5s: '',
        // video_play_10s: '',
        // video_play_15s: '',
        // video_play_30s: '',
        // video_play_60s: '',
        video_play_25p: 'video25',
        video_play_50p: 'video50',
        video_play_75p: 'video75',
        video_play_100p: 'video100',
      },

      slide_click: {
        // slide1_click: '',
        // slide2_click: '',
        // slide3_click: '',
        // slide4_click: '',
        // slide5_click: '',
        // slide6_click: '',
        // slide7_click: '',
        // slide8_click: '',
        // slide9_click: '',
        // slide10_click: '',
        // slide_others_click: '',
      },

      message_click: {
        // msg_click_share: '',
        // msg_click_media: '',
        // msg_click_title: '',
        // msg_click_text: '',
        // msg_play_start: '',
        // msg_play_3s: '',
        // msg_play_5s: '',
        // msg_play_10s: '',
        // msg_play_15s: '',
        // msg_play_30s: '',
        // msg_play_60s: '',
        // msg_click_list1: '',
        // msg_click_list2: '',
        // msg_click_list3: '',
        // msg_click_list4: '',
        // msg_play_list1_start: '',
        // msg_play_list1_3s: '',
        // msg_play_list1_5s: '',
        // msg_play_list1_10s: '',
        // msg_play_list1_15s: '',
        // msg_play_list1_30s: '',
        // msg_play_list1_60s: '',
        // msg_play_list2_start: '',
        // msg_play_list2_3s: '',
        // msg_play_list2_5s: '',
        // msg_play_list2_10s: '',
        // msg_play_list2_15s: '',
        // msg_play_list2_30s: '',
        // msg_play_list2_60s: '',
        // msg_play_list3_start: '',
        // msg_play_list3_3s: '',
        // msg_play_list3_5s: '',
        // msg_play_list3_10s: '',
        // msg_play_list3_15s: '',
        // msg_play_list3_30s: '',
        // msg_play_list3_60s: '',
        // msg_play_list4_start: '',
        // msg_play_list4_3s: '',
        // msg_play_list4_5s: '',
        // msg_play_list4_10s: '',
        // msg_play_list4_15s: '',
        // msg_play_list4_30s: '',
        // msg_play_list4_60s: '',
        // msg_click_button1: '',
        // msg_click_button2: '',
        // msg_click_carousel_button1: '',
        // msg_click_carousel_button2: '',
        // msg_click_carousel_button3: '',
        // msg_click_carousel_button4: '',
        // msg_click_carousel_button5: '',
        // msg_click_carousel_button6: '',
        // msg_click_carousel_share1: '',
        // msg_click_carousel_share2: '',
        // msg_click_carousel_share3: '',
        // msg_click_carousel_share4: '',
        // msg_click_carousel_share5: '',
        // msg_click_carousel_share6: '',
        // msg_click_carousel1_coupon: '',
        // msg_click_carousel2_coupon: '',
        // msg_click_carousel3_coupon: '',
        // msg_click_carousel4_coupon: '',
        // msg_click_carousel5_coupon: '',
        // msg_click_carousel6_coupon: '',
        // msg_click_carousel_more: '',
        // msg_click_coupon: '',
        // msg_click_others: '',
      },

      adview: {
        // ADV_CLICK_BUTTON1: '',
        // ADV_CLICK_BUTTON2: '',
        // ADV_CLICK_BUTTON_SHARE: '',
        // ADV_TH1_VIEW: '',
        // ADV_TH1_VIDEO_PLAY_AUTO: '',
        // ADV_TH1_VIDEO_PLAY_TOUCH: '',
        // ADV_TH1_VIDEO_PLAY_3S: '',
        // ADV_TH2_VIEW: '',
        // ADV_TH2_VIDEO_PLAY_AUTO: '',
        // ADV_TH2_VIDEO_PLAY_TOUCH: '',
        // ADV_TH2_VIDEO_PLAY_3S: '',
        // ADV_TH3_VIEW: '',
        // ADV_TH3_VIDEO_PLAY_AUTO: '',
        // ADV_TH3_VIDEO_PLAY_TOUCH: '',
        // ADV_TH3_VIDEO_PLAY_3S: '',
        // ADV_TH4_VIEW: '',
        // ADV_TH4_VIDEO_PLAY_AUTO: '',
        // ADV_TH4_VIDEO_PLAY_TOUCH: '',
        // ADV_TH4_VIDEO_PLAY_3S: '',
        // ADV_TH5_VIEW: '',
        // ADV_TH5_VIDEO_PLAY_AUTO: '',
        // ADV_TH5_VIDEO_PLAY_TOUCH: '',
        // ADV_TH5_VIDEO_PLAY_3S: '',
        // ADV_TH6_VIEW: '',
        // ADV_TH6_VIDEO_PLAY_AUTO: '',
        // ADV_TH6_VIDEO_PLAY_TOUCH: '',
        // ADV_TH6_VIDEO_PLAY_3S: '',
        // ADV_TH7_VIEW: '',
        // ADV_TH7_VIDEO_PLAY_AUTO: '',
        // ADV_TH7_VIDEO_PLAY_TOUCH: '',
        // ADV_TH7_VIDEO_PLAY_3S: '',
        // ADV_TH8_VIEW: '',
        // ADV_TH8_VIDEO_PLAY_AUTO: '',
        // ADV_TH8_VIDEO_PLAY_TOUCH: '',
        // ADV_TH8_VIDEO_PLAY_3S: '',
        // ADV_TH9_VIEW: '',
        // ADV_TH9_VIDEO_PLAY_AUTO: '',
        // ADV_TH9_VIDEO_PLAY_TOUCH: '',
        // ADV_TH9_VIDEO_PLAY_3S: '',
        // ADV_TH10_VIEW: '',
        // ADV_TH10_VIDEO_PLAY_AUTO: '',
        // ADV_TH10_VIDEO_PLAY_TOUCH: '',
        // ADV_TH10_VIDEO_PLAY_3S: '',
      },

      biz_board: {
        // EXPANDABLE_IMP: '',
        // MOTION_VIDEO_PLAY_AUTO: '',
        // EXPANDABLE_VIDEO_PLAY_AUTO: '',
        // MOTION_VIDEO_PLAY_3S: '',
        // EXPANDABLE_VIDEO_PLAY_3S: '',
        // EXPANDABLE_CLICK_CTA: '',
        // EXPANDABLE_CLICK_IMAGE1: '',
        // EXPANDABLE_VIEWABLE_GOODS_1: '',
        // EXPANDABLE_VIEWABLE_GOODS_2: '',
        // EXPANDABLE_VIEWABLE_GOODS_3: '',
        // EXPANDABLE_VIEWABLE_GOODS_4: '',
        // EXPANDABLE_VIEWABLE_GOODS_5: '',
        // EXPANDABLE_CLICK_GOODS_1: '',
        // EXPANDABLE_CLICK_GOODS_2: '',
        // EXPANDABLE_CLICK_GOODS_3: '',
        // EXPANDABLE_CLICK_GOODS_4: '',
        // EXPANDABLE_CLICK_GOODS_5: '',
      },

      spb: {
        // channel_home_click: '',
        // channel_add_click: '',
        // article1_click: '',
        // article2_click: '',
        // article3_click: '',
        // article4_click: '',
        // article5_click: '',
        // article6_click: '',
        // article7_click: '',
        // article8_click: '',
        // article9_click: '',
        // article10_click: '',
      },
    },
    keyword: {
      basic: {
        imp: 'impressions',
        click: 'clicksAll',
        ctr: 'ctr',
        spending: 'cost',
      },

      addition: {
        rimp: 'rimp',
        ppc: 'costPerImp',
        rank: 'avgRnk',
      },

      pixel_sdk_conversion: {
        convCmptReg1d: 'completedRegistration1D',
        convCmptReg7d: 'completedRegistration7D',
        convViewCart1d: 'viewCart1D',
        convViewCart7d: 'viewCart7D',
        convPurchase1d: 'purchase1D',
        convPurchase7d: 'purchase7D',
        // convPurchaseP1d: '',
        // convPurchaseP7d: '',
        convParticipation1d: 'participation1D',
        convParticipation7d: 'participation7D',
        // convSignup1d: '',
        // convSignup7d: '',
        convAppInstall1d: 'appInstall1D',
        convAppInstall7d: 'appInstall7D',
      },
    },
  },

  naver: {
    impCnt: 'impressions',
    clkCnt: 'clicksAll',
    salesAmt: 'pixelRevenue',
    ctr: 'ctr',
    cpc: 'cpc',
    avgRnk: 'avgRnk',
    // ccnt: '',
    // recentAvgRnk: '',
    // recentAvgCpc: '',
    // pcNxAvgRnk: '',
    // mblNxAvgRnk: '',
    crto: 'cvr',
    convAmt: 'conversionValue',
    // ror: '',
    cpConv: 'cpa',
    // viewCnt: '',
  },
};

module.exports = mapping;
